# -*- coding: utf-8 -*-
"""Image to caption .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pTGkzcYAhme85NQ7kA15gPn28vqD16wU
"""

#Image to text
# Install required libraries
#!pip install transformers
#!pip install pillow

from transformers import pipeline
from PIL import Image
from google.colab import files

# Upload image
uploaded = files.upload()
image_path = list(uploaded.keys())[0]  # Get the uploaded image filename

# Initialize the image captioning pipeline
image_captioning_pipeline = pipeline("image-to-text", model="Salesforce/blip-image-captioning-base")

# Open the uploaded image and test the pipeline
try:
    image = Image.open(image_path).convert("RGB")  # Ensure compatibility
    response = image_captioning_pipeline(image)
    print("Generated Caption:", response[0]['generated_text'])
except Exception as e:
    print("Error:", e)